# Server settings  
server:  
    port:8080  
    address:localhost  
  
# DATASOURCE - MYSQL
jdbc:  
    driver: com.mysql.jdbc.Driver  
    url: jdbc:h2:~/incidenthub
    username: root  
    password: root