# Server settings  
server:  
    port:8080  
    address:localhost  
  
# DATASOURCE - MYSQL
jdbc:  
    driver: com.mysql.jdbc.Driver  
    url: jdbc:h2:mem:way;DB_CLOSE_DELAY=-1
    username: root  
    password: root