# Server settings  
server:  
    port:8081  
    address:localhost  
  
# DATASOURCE  - Microsoft SQL Server
jdbc:  
    driver: com.mysql.jdbc.Driver  
    url: jdbc:mysql://127.0.0.1:3306/way?useUnicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false  
    username: root  
    password: root  